[package]
name = "bbd"
version = "0.4.1"
edition = "2024"
description = "Binary Braille Dump"
license = "MIT"
repository = "https://github.com/qtfkwk/bbd"

[dependencies]
bbd-lib = { version = "0.4.1", path = "../lib" }
clap = { version = "4.5.50", features = ["derive", "wrap_help"] }
clap-cargo = "0.18.3"
